function loadAssetsAndStartGame() {
	loader
	.add("images/sprites/active.png")
  .add("images/sprites/b_color.png")
  .add("images/sprites/b_forward.png")
  .add("images/sprites/b_left.png")
  .add("images/sprites/b_right.png")
  .add("images/sprites/ball.png")
  .add("images/sprites/color.png")
  .add("images/sprites/forward.png")
  .add("images/sprites/free.png")
  .add("images/sprites/goal.png")
  .add("images/sprites/green.png")
  .add("images/sprites/hint.png")
  .add("images/sprites/left.png")
  .add("images/sprites/level1.png")
  .add("images/sprites/red.png")
  .add("images/sprites/right.png")
  .add("images/sprites/run.png")
  .add("images/sprites/title.png")
  .add("images/sprites/wall.png")
  .add('images/spritesheets/spritesheet.json')
	.load(setupGame);
}